apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: {{ .Values.metadata.namespace }}
data:
  index.html: |
    <html>
    <h1>Welcome to our simple Lab! (brought by Helm) </h1>
    </html

