apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.nginxService.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30080
  selector:
    app: nginx

